---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

Data Analyst with experience in statistical modeling, data visualization, and stakeholder-focused insights. Skilled in R, Python, SQL, and storytelling translating complex datasets into actionable recommendations to improve business practices, customer engagement, and operational efficiency. 

# Professional Experience

**Sports Analyst**, New Brunswick, NJ    
_Rutgers University_ | August 2024 - Present  

*   Collect, clean, and analyze large datasets for B1G+ production teams and on-air personnel to provide real-time performance trends and insights for live broadcasts covering 20+ athletes per match 

*   Develop 15-20 dashboards and visual summaries using R, presenting findings to inform operational adjustments and enhancing broadcast commentary for 5,000+ viewers 

**Head Coach/Technical Coordinator**, West Nyack, NY    
_Pinnacle Volleyball Academy_ | December 2019 - Present  

*   Manage operational data and analysis reports for 100+ athletes across multiple age groups using player-level metrics to optimize program effectiveness 

*   Conduct systematic video and statistical analysis to evaluate player efficiency, success rates, and game impact to enhance player IQ and decision-making   

**Performance Analysis Contributor**, Orangeburg, NY    
_St. Thomas Aquinas College_ | August 2020 - November 2024  

*   Analyzed historical and operational data using opponent statistics and film, to identify offensive/defensive patterns and trends, providing actionable recommendations  

*   Collaborated with staff and players, producing reports and visual summaries for presentations to understand key metrics and implement tactical adjustments     

# Research and Applied Data Projects

**Perfluorinated Substances Exposure and Metabolomic Signatures in Cord Blood Samples from the World Trade Center Birth Cohort: A Statistical Analysis Comparing Non-Targeted and Targeted Assays
**   
Advisor: Julie Herbstman, MSc, PhD and Kendall Krutchen, MPH  

*   Conducted advanced regression analyses from large, complex datasets, comparing targeted and non-targeted assays between per- and polyfluorinated substances

*   Visualized complex datasets for trend analysis, enhancing decision-making for intervention strategies


**Elk Expeditions: The Elk, the Environment, and the Evolving Migration in Yellowstone**   
Advisor: Jeff Goldsmith, PhD   

*   Analyzed GPS movement data of 17 female elk in Wyoming across 9 years (2006-2015) using R

*   Built an interactive Shiny application, visualizing migration patterns of 3 environmental variables: weather, land cover, and water quality

**Conspicuous Consumption and the Role of the Fast Fashion Industry in Consumer Behavior**      	
_A Case Study of H&M, Zara, and Shein_    
Advisor: Robert Lacey, PhD

*   Conducted statistical analyses to evaluate market strategies and customer purchasing behavior in the fast fashion industry using survey and market data, providing insights on drivers influencing demand 

*   Interpreted model outputs to recommend cost-effective strategies for engagement and sales optimization    

# Education

**Columbia University Mailman School of Public Health**, New York, NY       
**Master of Science**, Environmental Health Data Science    

**Iona University**, New Rochelle, NY     
**Bachelor of Science**, Economics    
**Bachelor of Arts**, Political Science/Public Policy Track   
**Bachelor of Arts**, International Studies       


# Skills and Certifications

**Programming and Analytics**: R/R Studio, Python, Excel, Shiny, SQL
**Language Skills**: English, Spanish   
**Certifications**: Biomedical Research, Social/Behavioral Research, Human Subjects Protection Biomed       

